sudo: required
services:
- docker
before_install:
- git clone --recursive https://github.com/frankj2222/DualBootPatcher -b master DualBootPatcher/
- docker pull yshalsager/dualbootpatcher:9.3.0-7-base
#- docker pull yshalsager/dualbootpatcher:9.3.0-7-android
- docker pull yshalsager/dualbootpatcher:9.3.0-7-mingw
script:
- mkdir $HOME/.android
- mkdir -p ${TRAVIS_BUILD_DIR}/DualBootPatcher/builder/ && cd ${TRAVIS_BUILD_DIR}/DualBootPatcher/
- |
  #docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/builder/DualBootPatcher:rw,z" -v "${HOME}/.android:/builder/.android:rw,z" yshalsager/dualbootpatcher:9.3.0-7-android bash << EOF
  #cd DualBootPatcher/builder && cmake .. -DMBP_BUILD_TARGET=android -DMBP_BUILD_TYPE=debug && make -j16 && rm -rf assets && cpack && make apk -j16
  #make android-system_armeabi-v7a -j16 && make -C data/devices -j16
  #exit
  #EOF
- |
  docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/builder/DualBootPatcher:rw,z" -v "${HOME}/.android:/builder/.android:rw,z" yshalsager/dualbootpatcher:9.3.0-7-mingw bash << EOF
  # Build Utilities Zip
  cd ~/DualBootPatcher/builder && ./utilities/create.sh
  # Build Linux
  cmake .. -DMBP_BUILD_TARGET=desktop -DMBP_PORTABLE=ON && make -j16 && cpack
  exit
  EOF
after_success:
  - export TRAVIS_CURRENT_DATE=$(date +"%d%m%y-%Hh%Mm")
  # Check output & md5sum
  - ls -l ${TRAVIS_BUILD_DIR}/DualBootPatcher/Android_GUI/build/outputs/apk/debug/Android_GUI-debug.apk
  - md5sum ${TRAVIS_BUILD_DIR}/DualBootPatcher/Android_GUI/build/outputs/apk/debug/Android_GUI-debug.apk
  - ls -l ${TRAVIS_BUILD_DIR}/DualBootPatcher/builder/utilities/DualBootUtilities-9.3.0.zip
  - md5sum ${TRAVIS_BUILD_DIR}/DualBootPatcher/builder/utilities/DualBootUtilities-9.3.0.zip
  - ls -l ${TRAVIS_BUILD_DIR}/DualBootPatcher/builder/DualBootPatcher-9.3.0-Win32.zip
  - md5sum ${TRAVIS_BUILD_DIR}/DualBootPatcher/builder/DualBootPatcher-9.3.0-Win32.zip
  # Upload to transfer.sh
  - cd ${TRAVIS_BUILD_DIR}/DualBootPatcher/Android_GUI/build/outputs/apk/debug/ &&  curl --upload-file ./Android_GUI-debug.apk https://transfer.sh/Android_GUI-debug-${TRAVIS_CURRENT_DATE}.apk
  - cd ${TRAVIS_BUILD_DIR}//DualBootPatcher/builder/utilities/ && curl --upload-file ./DualBootUtilities-9.3.0-${TRAVIS_CURRENT_DATE}.zip https://transfer.sh/DualBootUtilities-9.3.0-${TRAVIS_CURRENT_DATE}.zip
  - cd ${TRAVIS_BUILD_DIR}/DualBootPatcher/builder/ && curl --upload-file ./DualBootPatcher-9.3.0-Win32.zip https://transfer.sh/DualBootPatcher-9.3.0-${TRAVIS_CURRENT_DATE}-Win32.zip
env:
  global:
    secure: wzgbRLdEO/oGjlNy9qJGxDcJpkUBJfKt9KrBx6nEA6fyD3ncuv8r6ukc+jtBTueqNfEW+cDN75CyB+S8sMGctluKVLdcidC/JooUfiS8l5B5V6IlTYWbuPuoxPU18WTSUpZwvqz+FbRbng2KyMzQ7s3QqxsNA0O9Z+XxjEU4gaGTHz8NJ/4BxFgjoG7eKQ2dALL82FCVq6fEhPucgJ9rzJqycjGRpi8H8fDvJlNU9mAK7aOz8ukyP43E4i/r7vhXkS08Hk1ut9aEqG4Khw3PlQqw9qMuRH1UNoSGM8MVyjBTdyLyaoLR1D+94gATRiCta/OLi1/pJEZ7xlnv7F4/y42dEqnXJFMJZq7GQ3c8qNlxc1+ABf/Kl7fEZ/ROzlvf1espXjdcKNQZdNUtYPcDQMHCphBeYMIz5vcw11FsIIM1/j1qpGOXtmzHfuIWDw7a7o8YupC8uDCvewkpqxGz10dwJVvTzzzrekbaqQRKXezLhRoVZrQJM5unrHoeb0pXSnj0MxRRWJgWykHyRTepgLVxZ7LN9yU1ZMZqtAmAyaioehh5XCGpz5Kr0X55tUjTpEKNlGfo0bW85r9pYMN6bfNfSMFSpYLGGHGPgjyL8gnXUweDztLlAxiPx/8/TG+xf+ZuVNlSnbStJL4OB8420094ylbRLvk7gvi0z1XXLIo=
deploy:
  provider: releases
  api_key:
    secure: HdHjUAHbDIcXAIvmBhJU0OTrBpGn7fy6aPkLHF/X99qkuUvDYMM+OPyj//R3elX04pnWIHSs4r3ffGGwj+EJ5mnvkqJYVW2Svi7MJZJLCooYCCJ5r7HjhLq0EtdmU4Ea1ieNuH6niM9RYqKsv+/1d+Hxjw9JfJ6asfqCqXTJiTETEKO2//QDXMw8iRag0XG1Be52/hGhfBVbvgvaOlxTCxjycnC9X1zru+CiFf0qe2BK/xfA8QxZ6J3lHLr8W4/LsMg2450vLfljyqO8clPzH95qAkuKfZPj/+MkLeyIGWUfUHSzY/NkbRJxmpmCqRDQVBNXTAjVwSBr28XqevjL1W45rMjog5DbObYEv4BIocRjeNQ7saVwC0l7ox+KwClcTlMcJTwGVoHJj1ueWIfL0i8aoGMymyAxDfe3ccT/cLdmRvfP1xFczENSjSt76px/rS52D40mZ3vf6GZUtCWOrVtOiX+Cjsoq8FiJ02sIT46QPcsORgVxo24UcLtirdXV5Ok6zg/O3yJYFPFkmX55S8aSoDR4qt3ZGxsxXdUAm4pjuuqDZ1KDEYWD2zcb6NXQ+YcRb8TxWUuMr2sPVl1kOteUgjZmmLCsOYdyTcp8YyanySo3C4jj4TDbJ3N5W1amsIlQ56+hLsR1YYPMY0NpZtTzdJgbUCn/bC3AnvF7q/s=
  file: DualBootPatcher-9.3.0-Win32.zip
  on:
    repo: frankj2222/DualBootPatcher
